#!/bin/bash
# This script publishes the Helm chart to the JupyterHub Helm chart repo and
# pushes associated built docker images to Docker hub using chartpress.
# --------------------------------------------------------------------------

# Exit on errors, assert env vars, log commands
set -eux

PUBLISH_ARGS="--push \
    --builder docker-buildx \
    --platform linux/amd64 --platform linux/arm64 \
"

cd helm-chart
chartpress $PUBLISH_ARGS --image-prefix=quay.io/depositar/k8s-

# Let us log the changes chartpress did, it should include replacements for
# fields in values.yaml, such as what tag for various images we are using.
git --no-pager diff --color=always
