name: Publish helm chart and docker images

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "docs/**"
      - "examples/**"
      - ".github/workflows/**"
      - "!.github/workflows/publish.yml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
      - "update-*"
  workflow_dispatch:

jobs:
  # Builds and pushes docker images to quay.io, packages the Helm chart and
  # pushes it to jupyterhub/helm-chart@gh-pages where index.yaml represents the
  # JupyterHub organization Helm chart repository.
  #
  # ref: https://github.com/jupyterhub/helm-chart
  # ref: https://quay.io/organization/jupyterhub
  #
  Publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release-depositar'
    steps:
      - uses: actions/checkout@v4
        with:
          # chartpress requires the full history
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/setup-node@v4
        # node required to build wheel
        with:
          node-version: "16"

      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (for chartpress multi-arch builds)
        uses: docker/setup-buildx-action@v3

      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: "v3.5.4"

      - name: Install chart publishing dependencies (chartpress, etc)
        run: |
          pip install --no-cache-dir chartpress>=2.1 pyyaml build

      - name: Build binderhub wheel
        run: python3 -m build --wheel .

      - name: Setup push rights to Quay.io
        # This was setup by...
        # 1. Creating a [Robot Account](https://quay.io/organization/depositar?tab=robots) in the JupyterHub
        # .  quay.io org
        # 2. Giving it enough permissions to push to the binderhub image
        # 3. Putting the robot account's username and password in GitHub actions environment
        run: |
          docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Publish images and chart with chartpress
        run: |
          ./ci/publish
